### ISSUE TITLE
Policies of type `data` are not being rendered in HTML reports

### ISSUE THREAD

**Issue by bschilt** [seanhamlin/site-audit#193] opened 2018-06-22 13:41 UTC
When running a profile that contains `data` policies the resulting report does not include them. 

It looks like a regression was introduced by this commit: https://github.com/drutiny/drutiny/commit/ee362bfcb4f9eb390b0003f1328dc2c0c89f6268

**Comment by fiasco** [comment] 2018-06-22 19:55
Ah yes, looks like thats a regression and its not quick to fix without regressing what that change fixed.

I've tagged 2.2.1 on the ref before that regression occurs as a temporary workaround.

**Comment by fiasco** [comment] 2018-12-11 19:23
Fixed now. Closing.

**Closed as completed by fiasco** 2018-12-11 19:23 UTC
